############# English navigation ##############

[[main]]
name = "About Us"
url = "/about.html"
weight = 1

[[main]]
name = "Roadmap"
url = "/roadmap.html"
weight = 2

[[main]]
name = "Download"
url = "/programs.html"
weight = 3

[[main]]
name = "Q&A"
url = "/q-and-a.html"
weight = 4

[[main]]
name = "Blog"
url = "/publications/"
weight = 5

[[main]]
name = "Contact"
url = "/contact.html"
weight = 6
